# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: balbuildandreleasetask@0
  inputs:
    samplestring: 'https://nodejs.org/dist/v16.9.1/node-v16.9.1.pkg'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
