# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: build.yml

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: build.yml

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: build.yml
