steps:
- script: |
    curl -o ballerina.deb 'https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-linux-x64.deb'
    sudo dpkg -i ballerina.deb
    rm -f ballerina.deb
    bal -v
  displayName: Install Ballerina(Linux)
  condition: eq(variables['Agent.OS'], 'Linux')

- script: |
    curl -o ballerina.pkg 'https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-macos-x64.pkg'
    sudo installer -pkg ballerina.pkg -target /
    rm -f ballerina.pkg
    echo $PATH
    ls Library/Ballerina
    sudo find / -name "bal"
  displayName: Install Ballerina(MacOS)
  condition: eq(variables['Agent.OS'], 'Darwin')

- script: |
      curl -o ballerina.msi https://dist.ballerina.io/downloads/2201.6.0/ballerina-2201.6.0-swan-lake-windows-x64.msi
      msiexec /i ballerina.msi /quiet /qr /L*V "C:\Temp\msilog.log"
      del ballerina.msi
      type C:\Temp\msilog.log
      dir /s "C:bal.bat"
  displayName: Install Ballerina(Windows)
  condition: eq(variables['Agent.OS'], 'Windows_NT')

- script: |
    bal -v
  displayName: Display version